machines/urls.py
from django.urls import path 
from machines import views


app_name = 'machines'

urlpatterns = [
    # path('', views.all_machines, name='all-machines'),
    # path('detail/', views.show_detail_machines, name='detail_machines'),
    path('<int:id>/', views.detail_machine, name='detail'),
    path('description/', views.show_machines_description, name='show_machine_description'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from main import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('logout/', views.mylogout, name='mylogout'),

    path('machines/', include('machines.urls')),
    path('driver/', include('senior_driver.urls')),

    path('machinist/', include('senior_machinist.urls')),

    path('engineer/', include('engineer.urls')),
    path('director/', include('director.urls')),

    path('administrator/', include('administrator.urls')),
]

from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns


from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senior_driver/urls.py
from django.urls import path
from senior_driver import views


app_name = 'driver'

urlpatterns = [
    path('', views.home_page, name='home-page'),
    path('myreports/', views.show_my_reports, name='my_reports'),
    path('myreports/<int:report_id>', views.show_my_reports_detail, name='report-detail'),
    path('machines/', views.show_machines, name='machines'),
    path('about/', views.about, name='about'),

    path('report/', views.make_report, name='make-report'),
    path('report/fill/', views.make_report_fill, name='make-report-fill'),
]

engineer/models.py
from django.db import models
from django.contrib.auth.models import User

from senior_driver.models import SeniorDriver
from machines.models import Machine


class Engineer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True, null=False)
    telephone1 = models.CharField(max_length=15, blank=True, default='')
    telephone2 = models.CharField(max_length=15, blank=True, default='')
    avatar = models.ImageField(blank=True, upload_to="employees")


    def full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.user.username}"


class Report(models.Model):
    """ Таблиця Report - звіти від старших водіїв """
    
    filled_up = models.ForeignKey(SeniorDriver, on_delete=models.CASCADE)
    date_of_completion = models.DateTimeField(auto_now_add=True)
    updated_data = models.DateTimeField(auto_now=True)
    date = models.DateField()

    checked = models.BooleanField(blank=True, default=False)
    checked_by = models.ForeignKey(Engineer, on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return f"{self.filled_up} - {self.date}"

class MachineReport(models.Model):
    """ Таблиця MachineReport - які машини були використані в ході робочого дня """
    
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    
    name = models.CharField(max_length=200, blank=True)
    
    motohour = models.FloatField()
    fuel = models.FloatField()
    
    breakage = models.BooleanField(default=False)
    breakage_info = models.TextField(blank=True, null=True)
    breakage_date_start = models.DateField(blank=True, null=True)

    latFld = models.FloatField(blank=True, null=True)
    lngFld = models.FloatField(blank=True, null=True)


    def __str__(self):
        return f"{self.report.date} - {self.machine}"

    def machine_name(self):
        return f"{self.machine.full_name()}"
    

senior_driver/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class SeniorDriver(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True, null=False)
    brigade_name = models.CharField(blank=True, max_length=50)
    telephone1 = models.CharField(max_length=15, blank=True, default='')
    telephone2 = models.CharField(max_length=15, blank=True, default='')
    avatar = models.ImageField(blank=True, upload_to="employees")

    def full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.user.username}"

senior_driver/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q, Sum
from django.conf import settings

from machines.models import Machine
from engineer.models import Report, MachineReport, Engineer
from director.models import Director
from senior_driver.models import SeniorDriver
import datetime


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def home_page(request):
    """ Початкова сторінка бригадира """

    return render(request, 'senior-driver/home_page.html', context={})


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def about(request):
    
    driver = set_driver(request.user)
    engineers = Engineer.objects.all().select_related('user')
    directors = Director.objects.all().select_related('user')
    context = {
        'driver': driver,
        'engineers': engineers,
        'directors': directors,
    }
    return render(request, 'senior-driver/about_page.html', context)


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def show_my_reports(request):
    """ Звіти старшого водія """
    
    driver = set_driver(request.user)
    my_reports = Report.objects.filter(filled_up=driver).order_by('-id')
    
    if request.GET.get('from') and request.GET.get('to'):
        from_date = request.GET.get('from')
        to_date = request.GET.get('to')
        from_date_correct = correct_date(from_date)
        to_date_correct = correct_date(to_date)
        my_reports = my_reports.filter(date__range = [from_date_correct, to_date_correct])
    else:
        from_date = correct_date(my_reports.earliest('date').date, choise=2)
        to_date = correct_date(my_reports.latest('date').date, choise=2)

    
    # my_reports = add_machines(my_reports)

    context = {
        'from_date': from_date,
        'to_date' : to_date,
        'my_reports': my_reports
    }
    return render(request, 'senior-driver/my_reports.html', context)


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def show_my_reports_detail(request, report_id):
    """ Детально про звіт """
    
    driver = set_driver(request.user)

    try:
        report = Report.objects.select_related('filled_up', 'filled_up__user').get(pk=report_id)
    except:
        raise Http404("Звіт не знайдений")
    if report.filled_up != driver:
        raise Http404("Звіти зробив інший машиніст. Ви не маєте доступа до цього звіту!")


    machinereports = MachineReport.objects.filter(report_id=report.id).select_related('machine', 'machine__machine')

    data_for_js = []

    breakage = False
    
    for machinereport in machinereports:
        if machinereport.breakage:
            breakage = True

        if machinereport.latFld and machinereport.lngFld:
            data = [machinereport.name, machinereport.latFld, machinereport.lngFld]
            data_for_js.append(data)
    
    
    if len(data_for_js) > 1:
        lat_arr = [el[1] for el in data_for_js]
        lng_arr = [el[2] for el in data_for_js]
        center_lat = sum(lat_arr)/len(lat_arr)
        center_lng = sum(lng_arr)/len(lng_arr)
        center = {"lat": center_lat, "lng": center_lng}
    elif len(data_for_js) == 1:
        center = {"lat": data_for_js[0][1], "lng": data_for_js[0][2]}
    else:
        center = {"lat": 50.443165, "lng": 30.485434}
    
    context = {
        'report': report,
        'machinereports': machinereports,
        'data_for_js': data_for_js,
        'center_map': center,
        'breakage': breakage, 

        'google_api_key': settings.GOOGLE_MAPS_API_KEY,
    }
    
    return render(request, 'senior-driver/my_reports_detail.html', context)


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def show_machines(request):
    """ Машини які належать машиністу """
    
    driver = set_driver(request.user)
    my_machines = Machine.objects.filter(brigade=driver).select_related('machine')
    
    context = {
        'my_machines': my_machines.all(),
    }

    return render(request, 'senior-driver/my_machines.html', context)


@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def make_report(request):
    """ Створення звіту """

    driver = set_driver(request.user)
    
    all_machines = Machine.objects.filter(brigade=driver)

    can_use_machines = all_machines.filter(breakage=False)
    broken_machines = all_machines.filter(breakage=True).values('id', 'machine__name', 'number_machine', 'inventory_number')

    days, count = 30, 5
    last_used_machines = can_use_machines.filter(
            last_used_data__range=[datetime.date.today() - datetime.timedelta(days), datetime.date.today()]
        ).values('id', 'machine__name', 'number_machine', 'inventory_number'
        ).annotate(days=Sum('work_days')
        ).order_by('-days')[:count]

    long_used_machines = can_use_machines.filter(
            ~Q(id__in=[o["id"] for o in last_used_machines])
        ).values('id', 'machine__name', 'number_machine', 'inventory_number')

    context = {
        'broken_machines': broken_machines,
        'last_used_machines': last_used_machines,
        'long_used_machines': long_used_machines,
        'date_today': datetime.date.today().strftime("%Y-%m-%d"),
    }

    return render(request, 'senior-driver/make_report.html', context)

@login_required
@permission_required('senior_driver.full_control', raise_exception=True)
def make_report_fill(request):
    
    
    date = request.POST.getlist('date')[0] if request.POST.getlist('date') else None

    context = {}
    
    if request.POST.get('selectMachines'):
        machine_id_list = list(map(lambda el: int(el), request.POST.getlist('choices')))
        machines = Machine.objects.filter(id__in=machine_id_list)

        context = {
            'date': date,
            'machines': machines,
            'machine': machines[0] if machines else None,

            'google_api_key': settings.GOOGLE_MAPS_API_KEY,
        }
    
    if request.POST.get('sendData'):
        
        report = get_or_create_report(request.POST.get('report_id'), date, request)
                
        fuel = request.POST.get('fuel')
        motohour = request.POST.get('motohour')
        machine_breakage = request.POST.get('breakage')
        machine_breakage_info = request.POST.get('breakage_info')
        

        this_machine_id = int(request.POST.get('this_machine'))
        
        machine_id_list = list(map(lambda el: int(el), request.POST.getlist('choices')))
        machine_id_list.remove(this_machine_id) 
        
        current_machine = Machine.objects.get(id=this_machine_id)

        current_machine.work_days += 1
        current_machine.last_used_data = date
        
        machine_report = MachineReport.objects.create(
            report = report,
            name = current_machine.name + ' №' + current_machine.number_machine,
            machine = current_machine,
            motohour = motohour,
            fuel = fuel,
        )

        if request.POST.get('latFld') and request.POST.get('lngFld'):
            machine_report.latFld = request.POST.get('latFld')
            machine_report.lngFld = request.POST.get('lngFld')

        if request.POST.get('breakage'):
            current_machine.breakage = True
            current_machine.breakage_info = machine_breakage_info
            current_machine.breakage_date = date

            machine_report.breakage = True
            machine_report.breakage_info = machine_breakage_info
            machine_report.breakage_date_start = date


        current_machine.save()
        machine_report.save()

        machines = Machine.objects.filter(id__in=machine_id_list)

        if not machines:
            return render(request, 'senior-driver/home_page.html', {'message': 'Звіт створений'})
        
        context = {
            'report_id': report.id,
            'date': date,
            'machines': machines,
            'machine': machines[0],

            'google_api_key': settings.GOOGLE_MAPS_API_KEY,
        }

    return render(request, 'senior-driver/make_report_fill.html', context)


### допоміжні методи ###
def correct_date(date, choise = 1):
    if choise == 1:
        date_list = date.split('.')
        date_correct = f"{date_list[2]}-{date_list[1]}-{date_list[0]}"
        return date_correct
    if choise == 2:
        return date.strftime("%d.%m.%Y")


def add_machines(reports):
    machines_all = Machine.objects.values('id', 'machine__name', 'number_machine', 'inventory_number', 'breakage_info')
    for report in reports:
        machines = []

        for machine in report.machinereport_set.values():
            
            m = machines_all.get(id=machine['machine_id'])
            machine_full_name =  f"{m['machine__name']} #{m['number_machine']} [IN{m['inventory_number']}] "
            fuel = machine['fuel']
            motohour = machine['motohour']
            if machine['breakage']:
                breakage = "Є несправність"
                breakage += f"<br>({m['breakage_info']})"  if m['breakage_info'] else ''
            else:
                breakage = "В робочому стані"
                
            
            machines_info = {
                'full_name': machine_full_name,
                'fuel': fuel,
                'motohour': motohour,
                'breakage': breakage,
            }
            machines.append(machines_info)
        report.machines = machines
    return reports


def set_driver(user):
    if user.is_superuser:
        return SeniorDriver.objects.all().select_related('user')[1]
    return user.seniordriver


def get_or_create_report(report_id, date, request):
    if report_id:
        report = Report.objects.get(id= report_id)
        return report

templates/senior-driver/_base_page_driver.html
{% extends 'base.html' %}
{% load static %}


{% block add_head_link %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    {% block add_head_link_2 %}
    {% endblock add_head_link_2 %}
{% endblock add_head_link %}




{% block title %}Старший водій{% endblock %}


{% block content %}
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-dark border-right" id="sidebar-wrapper">
            <div class="sidebar-heading text-light py-5">VMM Core Production</div>
            <div class="list-group list-group-flush">
            <a href="{% url 'driver:home-page' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-top"><i
                    class="fa fa-home"></i>Головна</a>
            <a href="{% url 'driver:make-report' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light"><i
                    class="fa fa-table"></i>Створити звіт</a>

            <a href="{% url 'driver:my_reports' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light"><i
                    class="fa fa-truck"></i>Мої звіти</a>
            <a href="{% url 'driver:machines' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-wrench"></i>Мої машини</a>
            <a href="{% url 'driver:about'%}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-calendar"></i>Додатки</a>
        </div>
    </div>
        <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <a class="nav-link text-light" href="#">Привіт, {{ user.username }}!</a>
                    <a class="nav-link text-warning" href="{% url 'mylogout' %}"><i
                            class="fa fa-arrow-right"></i>Вийти</a>
                </ul>
            </div>
        </nav>
        {% block content_page %}
        КОД ОСН СТРАНИЦЫ
        {% endblock content_page %}
    </div>

{% block add_another_html %}
{% endblock add_another_html %}


<style>
    body {
        overflow-x: hidden;
    }
    .fa {
        margin-right: 10px;
    }
    #sidebar-wrapper {
        min-height: 100vh;
        margin-left: -15rem;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
    }
    #sidebar-wrapper .sidebar-heading {
        padding: 0.875rem 1.25rem;
        font-size: 1.2rem;
    }
    #sidebar-wrapper .list-group {
        width: 15rem;
    }
    #page-content-wrapper {
        min-width: 100vw;
    }
    #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
    }
    @media (min-width: 768px) {
        #sidebar-wrapper {
            margin-left: 0;
        }
        #page-content-wrapper {
            min-width: 0;
            width: 100%;
        }
        #wrapper.toggled #sidebar-wrapper {
            margin-left: -15rem;
        }
    }
</style>    

{% block add_style %}
{% endblock add_style %}


{% block add_js %}
{% endblock add_js %}

{% endblock content %}

templates/senior-driver/home_page.html
{% extends 'senior-driver/_base_page_driver.html' %}

{% block content_page %}

    <div class="container-fluid">
        <h1 class="mt-4 text-center alert">Головна сторінка старшого машиніста</h1>
        <div class="content-text">
            <div class="row justify-content-center">
                <div class="col-10">
                    <ul class="alert">
                        <li>
                            <p>Основна функція програми для водія - <a href="{% url 'driver:make-report' %}">Заповнення звіту</a>.</p>
                            <p style="text-indent: 2em;">
                                Звіт створюється в кінці робочої зміни. В звіт вносяться дані машин, які належать Вам і які були 
                                використані в ході робочого дня. Для внесення даних треба обрати дату (по замовченню - це дата коли звіт заповнюється), вибрати необхідні машини і внести інформацію 
                                за кожною машиною. Це скільки мотогодин пройдено, скільки палива використано. Якщо робоча машина була 
                                зламана/є пошкодження потрібно вказати це у звіті. Після відправлення звіту інформація попадає до 
                                головного інженера і він приймає подальші рішення.</p>
                            <p>
                        </li>
                        <li><p>
                        У вкладці <a href="{% url 'driver:my_reports'%}">"Мої звіти"</a> Ви можете подивитись всі звіти, які були заповненні та передані до головного інженера.
                    </p>
                        </li>
                        <li><p>
                            Вкладка <a href="{% url 'driver:machines'%}">"Мої машини"</a> знаходиться інформація про машини, які Вам належать. 
                            Там Ви зможете подивитись дані і стан конкретної машини. 
                        </p></li>
                        <li><p>
                            Вкладка <a href="{% url 'driver:about'%}">"Додатки"</a> містить деяку Вашу інформацію, графік виходу на роботу, 
                            телефони та email-адреси для зв'язку з головним інженером і директором  
                        </p></li>
                    </ul>
                </div>
            </div>
            
        </div>
    </div>
{% endblock content_page %}


{% block add_style %}
    <style> 
        p{
            font-size: larger;
            text-align: justify;
            line-height: 2;
        }       
    </style>
{% endblock add_style %}

templates/senior-driver/make_report.html
{% extends 'senior-driver/_base_page_driver.html'%}

{% block title %}Створити звіт{% endblock %}

{% block content_page %}
    <div class="container-fluid">
        <h1 class="mt-4 text-center">Створення звіту</h1>
        <div class="content-text">
            <form action="{% url 'driver:make-report-fill' %}" method="POST">
                {% csrf_token %}
                <p class="pt-4 offset-1"><label for="date"><span style="font-size: larger; font-weight: bold;" class="pr-4">1.</span> <i class="fa fa-calendar" aria-hidden="true"></i><span style="font-size: larger;" class="pr-2"> Оберіть дату:</span></label>
                    <input type="date" value="{{ date_today }}" name="date" id="date" required></p>

                <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">2.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Оберіть колійні машини, які використовувались у цей день:</span></p>
                               
                  
                {% if last_used_machines %}
                    <p class="offset-2 text-info font-italic pb-2">Машини якими найчастіше використувались за останній місяць</p>
                    {% for machine in last_used_machines %}
                    <p class="offset-2"><input type="checkbox" name="choices" value="{{machine.id}}" id="machine{{machine.id}}">
                        <label for="machine{{machine.id}}">{{ machine.machine__name}} {{machine.number_machine}} [IN-{{machine.inventory_number}}]</label>
                    </p>
                    {% endfor %}
                    <p class="offset-2 text-info font-italic pb-2">Всі інші машини</p>
                {% endif %}
                
                <div class="row">
                    <div class="offset-2 col-8">
                        <div class="row">
                            {% for machine in long_used_machines %}
                            <div class="col-6 pb-3">
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="checkbox" name="choices" value="{{machine.id}}" id="machine{{machine.id}}">
                                    <label class="form-check-label" for="machine{{machine.id}}">{{ machine.machine__name}} {{machine.number_machine}} [IN-{{machine.inventory_number}}]</label>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                
                <input type="submit" class="offset-1 btn btn-primary d-block mt-3 mb-3" name="selectMachines" value="Продовжити">
            </form>

            {% if broken_machines %}
                <p class="offset-1 text-primary font-italic pt-4" style="font-size: larger;">Машини які не відображаються через їх знаходження у ремонті:
                <ul class="offset-1 pl-10">
                    {% for machine in broken_machines %}
                        <li class="pb-2">{{ machine.machine__name}} {{machine.number_machine}} {{machine.inventory_number}}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% endblock content_page %}

    

templates/senior-driver/my_machines.html
{% extends 'senior-driver/_base_page_driver.html'%}

{% block title %}Мої машини{% endblock %}

{% block content_page %}

    <div class="container-fluid">
        <h2 class="pt-5" style="text-align: center;">Машини які закріплні за Вами:</h2><br>

        {# НЕ СЛОМАННЫЕ МАШИНЫ #}
        {% if my_machines %}
        <div class="row justify-content-around">
            {% for my_machine in my_machines %}
            <div class="card m-2 shadow p-3 mb-5 bg-white rounded" style="width: 20rem;">
                <div class="card-body text-center">
                    <h5 class="card-title">{{my_machine.name}} #{{my_machine.number_machine}}</h5>
                    <hr>
                    <p class="card-text">Інвентарний номер: <b>{{my_machine.inventory_number}}</b></p>
                    <p class="card-text">Стан машини: {% if my_machine.breakage %}<span style="color: red; font-weight: bold;">В ремонті!</span>{% else %}<span style="color: green; font-weight: bold;">Робочий</span>{% endif %}</p>
                    <a href="{% url 'machines:detail' my_machine.id %}" class="btn btn-primary">Детальніше</a>
                </div>
                <img class="card-img-top" src="{{my_machine.machine.image.url}}" alt="{{my_machine.name}}">
            </div>
            {% endfor %}
        </div>
        {% else %}
        <h3 class="pt-5 pl-5">За Вами не числиться жодна машина!</h3>
        {% endif %}
    </div>

{% endblock content_page %}


{% block add_style %}
    <style>        
    </style>
{% endblock add_style %}

templates/senior-driver/my_reports_detail.html
{% extends 'senior-driver/_base_page_driver.html' %}
{% load static %}

{% block title %}Детально про звіт №{{report.id}}{% endblock %}

{% block content_page %}
    <div>
        <h2 class="mt-4 text-center">Детально про звіт</h2>

        <div class="row offset-3 col-6 justify-content-center pt-3">
            <div class="col-6 text-center pt-3">
                <p class="font-larger"><i class="fa fa-file" aria-hidden="true"></i> <span>Звіт №{{report.id}}</span></p>
            </div>
            <div class="col-6 text-center pt-3">
                <p class="font-larger"><i class="fa fa-calendar"></i> <span>{{report.date}}</span></p>
            </div>
        </div>
        <p class="text-center font-italic pt-4 mt-4 font-larger">Машини та дані про мотогодини і використане дизельне паливо</p>
        <div class="col-10 text-center offset-1">
        <table class="table">
            <tr>
                <th>Машина</th>
                <th>Мотогодини</th>
                <th>Використано дизелю</th>
            </tr>
            {% for machinereport in machinereports %}
            <tr>
                <td><a class="" href="{% url 'machines:detail' machinereport.machine.id %}">{{machinereport.machine}}</a></td>
                <td>{{machinereport.motohour}} мото/год</td>
                <td>{{machinereport.fuel}} л.</td>
            </tr>
            {% endfor %}
        </table>
        </div>

        <p class="text-center font-italic pt-3 font-larger">Інформація про несправності</p>
        {% if breakage %}  
        <ul class="offset-2 pl-10">
            {% for machinereport in machinereports %}
                {% if machinereport.breakage %}
                <li class="pb-2">{{machinereport.name}}<br>
                    <span class="font-italic">Інформація про несправність:</span> 
                    {% if machinereport.breakage_info %} 
                         <span class="text-danger font-italic"><b>{{ machinereport.breakage_info }}</b></span>
                    {% else %}
                        <span class="text-danger font-italic"><b>інформація вказана не була</b></span>
                    {% endif %}
                </li> 
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
            <p class="text-center">За даним звітом несправностей під час роботи виявлено не було</p>
        {% endif %}


        <p class="text-center font-italic pt-3 font-larger">Місця проведення робот</p>
        {% if data_for_js %}
            <p class="offset-2 col-8 text-center">На карті зображені місця виконання роботи. Наведіть на маркер <i class="fas fa-map-marker-alt" style="color: red;"></i>, щоб дізнатись яка саме машина брала участь у роботі на данній дільниці.
                <br>Маркери можуть бути віддаленні один від одного, використовуйте зумування
            </p>
        {% else %}
            <p class="text-center">Даних про місця де виконувались роботи невідома або не була вказана</p>
        {% endif %}
    </div>
    <div class="offset-1 col-10" id="map">

    </div>
    
{% endblock content_page %}

{% block add_style %}
<style>
    #map {
        height: 500px;
    }
    .font-larger{
        font-size: larger;
    }
  </style>
{% endblock add_style %}


{% block add_js %}
<script>

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 8,
            center: {{ center_map | safe }}
        });
        setMarkers(map);
    }
    
    var data = {{data_for_js  | safe }};
    
    function setMarkers(map) {
    
        for (var i = 0; i < data.length; i++) {
            var el = data[i];
            var marker = new google.maps.Marker({
                position: { lat: el[1], lng: el[2] },
                map: map,
                title: el[0],
            });
        }
    }
</script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&language=uk">
    </script>
{% endblock add_js %}