main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from main import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('logout/', views.mylogout, name='mylogout'),

    path('machines/', include('machines.urls')),
    path('driver/', include('senior_driver.urls')),

    path('machinist/', include('senior_machinist.urls')),

    path('engineer/', include('engineer.urls')),
    path('director/', include('director.urls')),

    path('administrator/', include('administrator.urls')),
]

from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns


from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senior_machinist/urls.py
from django.urls import path
from senior_machinist import views


app_name = 'machinist'

urlpatterns = [
    path('', views.home_page, name='home-page'),
    path('machine/', views.my_machine, name='machine'),
    path('machine/status/', views.machine_status, name='machine-status'),
    path('contact/', views.management_contact, name='management-contact'),
    path('members/', views.brigade_members, name='brigade-members'),
    path('route-sheet/', views.route_sheet, name='route-sheet'),
    path('route-sheet/machine-info', views.machine_working_fill, name='machine-fill'),
    path('show-route-sheets/', views.show_route_sheet, name='show-route-sheet'),
    path('route-sheet/<int:route_sheet_id>/', views.route_sheet_detail, name='route-sheet-detail'),
]

senior_machinist/models.py
from django.db import models
from django.contrib.auth.models import User
from machines.models import Machine
from engineer.models import Engineer


class SeniorMachinist(models.Model):
    """ Старший машиніст """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    brigade_name = models.CharField(blank=True, max_length=50)
    telephone1 = models.CharField(max_length=30, blank=True, default='')
    telephone2 = models.CharField(max_length=30, blank=True, default='')
    avatar = models.ImageField(blank=True, upload_to="employees", default='no-image.png')
    
    date_of_birth = models.DateField(blank=True, null=True)
    date_start_work = models.DateField(blank=True, null=True)

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, blank=True, null=True)

    def full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.user.username}"


class BrigadeMembers(models.Model):
    """ Члени бригади (підконтрольні машиністу) """

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    telephone1 = models.CharField(max_length=30, blank=True, default='')
    telephone2 = models.CharField(max_length=30, blank=True, default='')
    
    HELPER = 'hlp'
    MACHINIST = 'mnst'
    JOB_TITLE_CHOICES = [
        (HELPER, 'допоможний персонал'),
        (MACHINIST, 'машиніст'),
    ]
    job_title = models.CharField(
        max_length=4,
        choices=JOB_TITLE_CHOICES,
        default=MACHINIST,
    )

    seniormachinist = models.ForeignKey(SeniorMachinist, on_delete=models.CASCADE)

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class TempReport(models.Model):
    """ Таблиця Report - звіти від старших машиністів """
    
    filled_up = models.ForeignKey(SeniorMachinist, on_delete=models.CASCADE)
    date_of_completion = models.DateTimeField(auto_now_add=True)
    updated_data = models.DateTimeField(auto_now=True)
    date = models.DateField(unique=True)

    checked = models.BooleanField(blank=True, default=False)
    checked_by = models.ForeignKey(Engineer, on_delete=models.CASCADE, blank=True, null = True)

    NO = 'no'
    START = 'strt'
    PART = 'part'
    FULL = 'full'
    FORWARD_I = 'fwdi'
    CHECKED_I = 'chki'
    FORWARD_D = 'fwdd'
    CHECKED_D = 'chkd'
    STAGE_CHOICES = [
        (NO, 'Пустий звіт'),
        (START, 'Початок створення'),
        (PART, 'Частично заповнений'),
        (FULL, 'Заповнений'),
        (FORWARD_I, 'Відісланий інженеру'),
        (CHECKED_I, 'Звіт перевірений інженером'), 
        (FORWARD_D, 'Відісланий директору'),
        (CHECKED_D, 'Звіт перевірений директором'), 
    ]
    stage = models.CharField(
        max_length=4,
        choices=STAGE_CHOICES,
        default=NO,
    )

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)

  
    motohour = models.FloatField(blank=True, null=True)
    km = models.FloatField(blank=True, null=True)
    fuel = models.FloatField(blank=True, null=True)
    maslo = models.FloatField(blank=True, null=True)

    breakage = models.BooleanField(default=False)
    breakage_info = models.TextField(blank=True, null=True)
    breakage_date_start = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.filled_up} - {self.date}"


class BrigadeInfoReport(models.Model):
    """ Інформація про бригаду у звіті """

    member = models.ForeignKey(BrigadeMembers, on_delete=models.CASCADE)
    report = models.ForeignKey(TempReport, on_delete=models.CASCADE)
    date_time_from = models.DateTimeField(blank=True, null=True)
    date_time_to = models.DateTimeField(blank=True, null=True)
    
    NOT_ALLOWED = 'na'
    UNKNOW = 'uk'
    ALLOWED = 'al'
    HEALTH = 'hl'
    PASSED = 'ps'
    MEDICAL_CHECK = [
        (NOT_ALLOWED, 'не допущенний'),
        (ALLOWED, 'допущений'),
        (HEALTH, 'здоровий'),
        (PASSED, 'пройдено'),
        (UNKNOW, 'невідомо'),
    ]
    medical_check_before = models.CharField(
        max_length=2,
        choices=MEDICAL_CHECK,
        default=UNKNOW,
    )
    medical_check_after = models.CharField(
        max_length=2,
        choices=MEDICAL_CHECK,
        default=UNKNOW,
    )

    def __str__(self):
        return f"{self.member}"


class MachineWorkingReport(models.Model):
    """ Таблиця MachineWorkingReport - де машина працювала в ході робочого дня """

    report = models.ForeignKey(TempReport, on_delete=models.CASCADE)

    client = models.CharField(max_length=20, blank=True, null=True)
    station_from = models.CharField(max_length=50, blank=True, null=True)
    station_to = models.CharField(max_length=50, blank=True, null=True)
    departure_time = models.DateTimeField(blank=True, null=True)
    arrival_time = models.DateTimeField(blank=True, null=True)
    
    latFld = models.FloatField(blank=True, null=True)
    lngFld = models.FloatField(blank=True, null=True)
    time_from = models.DateTimeField(blank=True, null=True)
    time_to = models.DateTimeField(blank=True, null=True)

    place_working = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    workday_production = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return f"{self.report.date}"

class MasloInfoReport(models.Model):

    report = models.OneToOneField(TempReport, on_delete=models.CASCADE, blank=True, null=True)
    marka = models.CharField(max_length=30, blank=True, null=True)
    vidano = models.CharField(max_length=30, blank=True)
    maslo_before = models.FloatField(blank=True, null=True)
    maslo_after = models.FloatField(blank=True, null=True)
    info = models.CharField(max_length=200, blank=True, null=True)


class MotoAndFuelInfoReport(models.Model):
    
    report = models.OneToOneField(TempReport, on_delete=models.CASCADE, blank=True, null=True)
    motohour_before = models.FloatField(blank=True, null=True)
    motohour_after = models.FloatField(blank=True, null=True)
    km_before = models.FloatField(blank=True, null=True)
    km_after = models.FloatField(blank=True, null=True)
    info = models.CharField(max_length=200, blank=True, null=True)

templates/senior-machinist/brigade_members.html
{% extends 'senior-machinist/part/_base_page_machinist.html' %}

{% block title %}Працівники бригади{% endblock %}

{% block content_page %}
        <h2 class="text-center mt-4 mb-4">Працівники у Вашій бригаді</h2>

        {% if members %}
        <div class="col-8 offset-2 text-center pt-4">

          
        <table class="table">
                <tr>
                    <th>Прізвище</th>
                    <th>Ім'я</th>
                    <th>Телефони</th>
                </tr>
            
            {% for member in members %}
                <tr>
                    <td>{{member.last_name}}</td>
                    <td>{{member.first_name}}</td>
                    <td>{{member.phones}}</td>
                </tr>
            {% endfor %}
            </table>
        </div>  
        {% else %}
            <p>У вас немає жодного водія</p>
        {% endif %}
        
        
        
{% endblock content_page %}


{% block add_style %}
        <style>
            .font-larger{
                font-size: larger;
            }
                        
          </style>
{% endblock add_style %}

templates/senior-machinist/home_page.html
{% extends 'senior-machinist/part/_base_page_machinist.html' %}

{% block content_page %}
<div class="container-fluid">
    <h1 class="mt-4 text-center alert">Головна сторінка старшого машиніста</h1>
    <div class="content-text">
        <div class="row justify-content-center">
            <div class="col-10">
                <ul class="alert">
                    <li>
                        <p>Основна функція програми для водія - <a href="{% url 'machinist:route-sheet' %}">Заповнення маршрутного листа</a>.</p>
                        <p style="text-indent: 2em;">
                            Маршрутний лист створюється в кінці робочої зміни. В маршрутний лист вносяться дані машини, яка належать Вам і яка були 
                            використані в ході робочого дня, ділянки де працювала машина та штат бригади. Для внесення даних треба обрати дату, вибрати працівників бригади, які працювали в цей день. 
                            Після відправлення звіту інформація попадає до головного інженера і він приймає подальші рішення.</p>
                        <p>
                    </li>
                    <li><p>
                    У вкладці <a href="{% url 'machinist:show-route-sheet'%}">"Мої маршрутні листи"</a> Ви можете подивитись всі маршрутні листи, які були заповненні та передані до головного інженера.
                </p>
                    </li>
                    <li><p>
                        Вкладка <a href="{% url 'machinist:machine'%}">"Моя машина"</a> містить інформацію про машину, яка закріплна за Вами. 
                        Там Ви зможете подивитись дані і стан конкретної машини. 
                    </p></li>
                    <li><p>
                        Вкладка <a href="{% url 'machinist:machine-status'%}">"Стан машини"</a> містить інформацію про стан машини. 
                        На даній вкладці можна змінити стан машини, тобто якщо у машини є несправність, інформування технічного спеціаліста та інженера відбувається саме тут. 
                    </p></li>
                    <li><p>
                        Вкладка <a href="{% url 'machinist:management-contact'%}">"Керівництво"</a> містить деяку Вашу інформацію,
                        телефони та email-адреси для зв'язку з головним інженером і директором. А у вкладці <a href="{% url 'machinist:brigade-members'%}">"Працівники бригади"</a> 
                        знаходиться інформація по працівникам з Вашої бригади
                    </p></li>
                </ul>
            </div>
        </div>
        
    </div>
</div>
    
{% endblock content_page %}


{% block add_style %}
    <style> 
        p{
            font-size: larger;
            text-align: justify;
            line-height: 2;
        }       
    </style>
{% endblock add_style %}

templates/senior-machinist/route_sheet_create.html
{% extends 'senior-machinist/part/_base_page_machinist.html'%}

{% block title %}Створити звіт{% endblock %}

{% block content_page %}
    <div class="container-fluid">
        <h2 class="mt-4 mb-4 text-center">Створення маршрутного листа</h2>
        
        <div class="content-text">
            {% if stage == 'prepare' %}
            <form action="{% url 'machinist:route-sheet' %}" method="POST">
                {% csrf_token %}
                <p class="pt-4 offset-1"><label for="date"><span style="font-size: larger; font-weight: bold;" class="pr-4">1.</span> <i class="fa fa-calendar" aria-hidden="true"></i><span style="font-size: larger;" class="pr-2"> Оберіть дату:</span></label>
                    <input type="date" value="{{mydate}}" name="date" id="date" required></p>

                <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">2.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Оберіть працівників у Вашій бригаді, які приступили до роботи в цю дату:</span></p>
                               
                  
                    <p class="offset-4 text-info font-italic pb-2">Працівники бригади</p>     
                    
                    <div class="row">
                        <div class="offset-2 col-8">
                            <div class="row">
                                {% for member in members %}
                                <div class="col-6 pb-3">
                                    <div class="form-check form-check-inline">
                                        <input class="form-check-input" type="checkbox" name="choices" value="{{member.id}}" id="member{{member.id}}">
                                        <label class="form-check-label" for="member{{member.id}}">{{ member.last_name}} {{ member.first_name}}</label>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>

                <input type="submit" class="offset-1 btn btn-primary d-block mt-3 mb-3" name="sendDataFirst" value="Продовжити">
            </form>
            {% endif %}

            {% if stage == 'full' %}
                <p class="pt-4 text-center"><i class="fa fa-calendar" aria-hidden="true"></i><span style="font-size: larger;" class="pr-2">Дата {{date}}</span></p>
                
                {% if temp_report.stage == 'fwdi' %}
                    
                    <div class="col-8 offset-2 text-center mt-4 pt-4">
                        <p>
                            Маршрутний лист за цю дату уже створений і був переданий Вами інженеру.<br>
                            Змінити його неможливо!<br>
                        </p>
                        <p>Зміст маршрутного листа можете подивитись на сторінці <a href="{% url 'machinist:show-route-sheet'%}"><b>Мої маршрутні листи</b></a>, звіт має <b>№{{temp_report.id}}</b></p>
                    </div>
                    
                    
                    
                {% elif temp_report.stage == 'strt' or temp_report.stage == 'part' %}
                
                <p class="text-center" style="font-size: large; font-style: italic;">Вами були обрані працівники які працювали у цей день: {{members|join:", "}}</p>
                <div class="row">
                    <div class="col-7">

                        <p class="offset-1" {% if not exist_brigade_info_report %}id="BrigadeInfoReport"  style="font-size: larger;"{% endif %} style="font-size: larger;">
                            <span style="font-weight: bold;" class="pr-4">1.</span> 
                            <i class="fa fa-train" aria-hidden="true"></i>
                            <span {% if not exist_brigade_info_report %} class="hover underline" {% endif %} style="padding-right: 2ch;"> Дані про бригаду</span>
                            {% if exist_brigade_info_report %}
                                <i class='fas fa-check' style='color: green;'></i>
                            {% else %}
                                <i class='fas fa-times' style='color:red;'></i>
                            {% endif %}
                        </p> 
                        <p class="offset-1" {% if not exist_moto_fuel_info_report %}id="MotoAndFuelInfoReport"{% endif %} style="font-size: larger;">
                            <span style="font-weight: bold;" class="pr-4">2.</span> 
                            <i class="fa fa-train" aria-hidden="true"></i>
                            <span {% if not exist_moto_fuel_info_report %} class="hover underline" {% endif %} style="padding-right: 2ch;"> Показання спідометра, лічильника мотогодин</span>
                            {% if exist_moto_fuel_info_report %}
                                <i class='fas fa-check' style='color: green;'></i>
                            {% else %}
                                <i class='fas fa-times' style='color:red;'></i>
                            {% endif %}
                        </p>
                        <p class="offset-1" {% if not exist_maslo_info_report %}id="MasloInfoReport"{% endif %} style="font-size: larger;">
                            <span style="font-weight: bold;" class="pr-4">3.</span> 
                            <i class="fa fa-train" aria-hidden="true"></i>
                            <span {% if not exist_maslo_info_report %} class="hover underline" {% endif %} style="padding-right: 2ch;"> Рух паливно-мастильних матеріалів</span>
                            {% if exist_maslo_info_report %}
                                <i class='fas fa-check' style='color: green;'></i>
                            {% else %}
                                <i class='fas fa-times' style='color:red;'></i>
                            {% endif %}
                        </p>
                        
                        <p class="offset-1" {% if not exist_machine_working_report %}id="MachineWorkingReport" onclick="document.getElementById('myform').submit(); return false;"{% endif %} style="font-size: larger;">
                                <span style="font-weight: bold;" class="pr-4">4.</span> 
                                <i class="fa fa-train" aria-hidden="true"></i>
                                <span {% if not exist_machine_working_report %} class="hover underline" {% endif %} style="padding-right: 2ch;"> Дані про роботу машини</span>
                            {% if exist_machine_working_report %}
                                <i class='fas fa-check' style='color: green;'></i>
                            {% else %}
                                <i class='fas fa-times' style='color:red;'></i>
                            {% endif %}
                        </p>
                        <form action="{% url 'machinist:machine-fill'%}" method="POST" id='myform'>
                            {% csrf_token %}
                            <input type="hidden" name='temp_report_id' value="{{temp_report.id}}">
                            <input type="hidden" name='date' value="{{date}}">
                            <input type="hidden" name='msg' value="msg">
                            {% for member in members %}
                                <input type="hidden" name="member_id" value="{{member.id}}">
                            {% endfor %}
                        </form>
                    </div>
                    <div class="col-5 text-center">
                        <div class="col-10 mt-4">
                            <p class="text-center">Натисніть на пункт дані якого ще не заповненні (там де іконка <i class='fas fa-times' style='color:red;'></i>). Заповніть форму. При закінчені оформлення 4х пунктів, натисніть на кнопку нижче</p>
                        </div>
                        <div class="col-2"></div>
                        <div class="col-10">
                            <form action="{% url 'machinist:show-route-sheet' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="date" value="{{date}}">
                                <input type="hidden" name="temp_report" value="{{temp_report.id}}">
                                <input type="submit" class="text-center btn btn-warning" name="sendDataFinish" value="Завершити створення звіту">
                            </form>
                        </div>
                        
                    </div>
                </div>
                {% else %}
                    {{temp_report.stage}} | unknows stage
                {% endif %}

                <div class="BrigadeInfoReport_block" style="display: none;">
                    {% include 'senior-machinist/part/_brigade_info_report.html' %}
                </div>
                <div class="MotoAndFuelInfoReport_block" style="display: none;">
                    {% include 'senior-machinist/part/_moto_fuel_info_report.html'%}
                </div>
                <div class="MasloInfoReport_block" style="display: none;">
                    {% include 'senior-machinist/part/_maslo_info_report.html'%}
                </div>
                <div class="MachineWorkingReport_block" style="display: none;">
                    {% include 'senior-machinist/part/_machine_working_info_report.html'%}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content_page %}

{% block add_style %}
<style>
    .hover:hover{
        font-weight: bold;
        color: red;
    }
    .underline{
        text-decoration: underline;
    }
</style>
{% endblock add_style %}

{% block add_js %}
<script>
    $(document).ready(function(){
        $("#BrigadeInfoReport").click(function(){
            $(".BrigadeInfoReport_block").show()
            $(".MotoAndFuelInfoReport_block").hide()
            $(".MasloInfoReport_block").hide()
            $(".MachineWorkingReport_block").hide()
        })
        $("#MotoAndFuelInfoReport").click(function(){
            $(".BrigadeInfoReport_block").hide()
            $(".MotoAndFuelInfoReport_block").show()
            $(".MasloInfoReport_block").hide()
            $(".MachineWorkingReport_block").hide()
        })
        $("#MasloInfoReport").click(function(){
            $(".BrigadeInfoReport_block").hide()
            $(".MotoAndFuelInfoReport_block").hide()
            $(".MasloInfoReport_block").show()
            $(".MachineWorkingReport_block").hide()
        })
        $("#MachineWorkingReport").click(function(){
            $(".BrigadeInfoReport_block").hide()
            $(".MotoAndFuelInfoReport_block").hide()
            $(".MasloInfoReport_block").hide()
            $(".MachineWorkingReport_block").show()
        })
    }); 
</script>
{% endblock add_js %}

    

templates/senior-machinist/route_sheet_detail.html
{% extends 'senior-machinist/part/_base_page_machinist.html'%}
{% load static %}

{% block title %}Детально про звіт №{{route_sheet.id}}{% endblock %}

{% block content_page %}
    <div>
        <h2 class="mt-4 text-center">Детально про звіт</h2>

        <div class="row offset-3 col-6 justify-content-center pt-3">
            <div class="col-6 text-center pt-3">
                <p class="font-larger"><i class="fa fa-file" aria-hidden="true"></i> <span>Звіт №{{route_sheet.id}}</span></p>
            </div>
            <div class="col-6 text-center pt-3">
                <p class="font-larger"><i class="fa fa-calendar"></i> <span>{{route_sheet.date}}</span></p>
            </div>
        </div>
        <p class="text-center font-italic pt-4 mt-4 font-larger">Машина та дані про мотогодини і використане дизельне паливо</p>
        <div class="col-10 text-center offset-1">
        <table class="table">
            <tr>
                <th>Машина</th>
                <th>Пройдено кілометрів</th>
                <th>Пройдено мотогодин</th>
                <th>Використано палива</th>
            </tr>
            <tr>
                <td>{{route_sheet.machine|default:"невідомо"}}</td>
                <td>{{route_sheet.km|default:"невідомо"}}</td>
                <td>{{route_sheet.motohour|default:"невідомо"}}</td>
                <td>{{route_sheet.maslo|default:"невідомо"}}</td>
            </tr>
        </table>
        </div>

        <p class="text-center font-italic pt-4 mt-4 font-larger">1. Дані про бригаду</p>
        {% if brigade_info_reports %}
        <div class="col-10 text-center offset-1">
        <table class="table">
            <tr>
                <th>Посада</th>
                <th>Прізвище</th>
                <th>Початок роботи</th>
                <th>Кінець роботи</th>
                <th>Передрейсовий мед. огляд</th>
                <th>Післярейсовий мед. огляд</th>
            </tr>
            {% for brigade_info_report in brigade_info_reports%}
            <tr>
                <td>{{brigade_info_report.member.get_job_title_display|default:"невідомо"}}</td>
                <td>{{brigade_info_report.member}}</td>
                <td>{{brigade_info_report.date_time_from|date:'H:i'|default:"невідомо"}}</td>
                <td>{{brigade_info_report.date_time_to|date:'H:i'|default:"невідомо"}}</td>
                <td>{{brigade_info_report.get_medical_check_before_display|default:"невідомо"}}</td>
                <td>{{brigade_info_report.get_medical_check_after_display|default:"невідомо"}}</td>
            </tr>
            {% endfor %}
        </table>
        </div>
        {% else %}
            <p class="offset-1 mb-3 mt-3">Даних про бригаду немає</p>
        {% endif %}


        <p class="text-center font-italic pt-4 mt-4 font-larger">2. Показання спідометра, лічильника мотогодин</p>
        {% if moto_fuel_info_report %}
        <div class="row col-10 text-center offset-1">
            <div class="col-5">
                <table class="table table-bordered">
                    <tr>
                        <td rowspan="2" style="vertical-align: middle;">Показання спідометра, лічильника мотогодин при виїзді</td>
                        <td>{{moto_fuel_info_report.motohour_before|default:"невідомо"}} мт/г</td>
                    </tr>
                    <tr>
                        
                        <td>{{moto_fuel_info_report.km_before|default:"невідомо"}} км</td>
                    </tr>
                </table>
            </div>
            <div class="col-5 offset-1">
                <table class="table table-bordered">
                    <tr>
                        <td rowspan="2" style="vertical-align: middle;">Показання спідометра, лічильника мотогодин при поверненні</td>
                        <td>{{moto_fuel_info_report.motohour_after|default:"невідомо"}} мт/г</td>
                    </tr>
                    <tr>
                        <td>{{moto_fuel_info_report.km_after|default:"невідомо"}} км</td>
                    </tr>
                </table>
            </div>
        </div>
        {% else %}
            <p class="offset-1 mb-3 mt-3">Даних про показання спідометра, лічильника мотогодин немає</p>
        {% endif %}

        <p class="text-center font-italic pt-4 mt-4 font-larger">3. Рух паливно-мастильних матеріалів</p>
        {% if maslo_info_report %}
        <div class="col-10 text-center offset-1">
        <table class="table">
            <tr>
                <th>Марка</th>
                <th>Видано</th>
                <th>Залишок при виїзді</th>
                <th>Залишок при поверненні</th>
                <th>Примітки</th>
            </tr>
            <tr>
                <td>{{maslo_info_report.marka|default:"невідомо"}}</td>
                <td>{{maslo_info_report.vidano|default:"невідомо"}}</td>
                <td>{{maslo_info_report.maslo_before|default:"невідомо"}}</td>
                <td>{{maslo_info_report.maslo_after|default:"невідомо"}}</td>
                <td>{{maslo_info_report.info|default:"невідомо"}}</td>
            </tr>
        </table>
        </div>
        {% else %}
            <p class="offset-1 mb-3 mt-3">Даних про рух паливно-мастильних матеріалів немає</p>
        {% endif %}


        <p class="text-center font-italic pt-4 mt-4 font-larger">4. Дані про роботу машини</p>
        {% if brigade_info_reports %}
        <div class="col-10 text-center offset-1">
        <table class="table table-bordered">
            <tr>
                <th>Клієнт</th>
                <th>Станція відправлення</th>
                <th>Станція призначення</th>
                <th>Початку робіт у «вікно»</th>
                <th>Закінчення робіт у «вікно»</th>
                <th>Назва виконаних робіт</th>
                <th>Виробіток за робочий день</th>
            </tr>
            {% for machine_working_report in machine_working_reports%}
            <tr>
                <td>{{machine_working_report.client|default:"невідомо"}}</td>
                <td>{{machine_working_report.station_from|default:"невідомо"}}</td>
                <td>{{machine_working_report.station_to|default:"невідомо"}}</td>
                <td>{{machine_working_report.departure_time|date:'H:i'|default:"невідомо"}}</td>
                <td>{{machine_working_report.arrival_time|date:'H:i'|default:"невідомо"}}</td>
                <td>{{machine_working_report.description|default:"невідомо"}}</td>
                <td>{{machine_working_report.workday_production|default:"невідомо"}}</td>
            </tr>
            {% endfor %}
        </table>
        </div>
        {% else %}
            <p class="offset-1 mb-3 mt-3">Даних про роботу машини немає</p>
        {% endif %}

        <p class="text-center font-italic pt-3 font-larger">Місця проведення робот</p>
        {% if data_for_js %}
            <p class="offset-2 col-8 text-center">На карті зображені місця виконання роботи. Наведіть на маркер <i class="fas fa-map-marker-alt" style="color: red;"></i>, щоб дізнатись які роботи проводились на данній дільниці.
                <br>Маркери можуть бути віддаленні один від одного, використовуйте зумування
            </p>
        {% else %}
            <p class="text-center">Даних про місця де виконувались роботи невідома або не була вказана</p>
        {% endif %}
    </div>
    <div class="offset-1 col-10" id="map">

    </div>
    
{% endblock content_page %}

{% block add_style %}
<style>
    #map {
        height: 500px;
    }
    .font-larger{
        font-size: larger;
    }
  </style>
{% endblock add_style %}


{% block add_js %}
<script>

    function initMap() {
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 8,
            center: {{ center_map | safe }}
        });
        setMarkers(map);
    }
    
    var data = {{data_for_js  | safe }};
    
    function setMarkers(map) {
    
        for (var i = 0; i < data.length; i++) {
            var el = data[i];
            var marker = new google.maps.Marker({
                position: { lat: el[1], lng: el[2] },
                map: map,
                title: el[0],
            });
        }
    }
</script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{google_api_key}}&callback=initMap&language=uk">
    </script>
{% endblock add_js %}