engineer/urls.py
from django.urls import path
from engineer import views


app_name = 'engineer'

urlpatterns = [
    path('', views.hello_page, name='home-page'),
    path('unforwarded_reports/', views.show_unforwarded_reports, name='unforwarded_reports'),
    path('forwarded_reports/', views.show_forwarded_reports, name='forwarded_reports'),
    path('drivers/', views.show_drivers, name='drivers'),
    path('drivers/<str:username>/', views.show_drivers_detail, name='driver_detail'),
    path('workdays/', views.work_days, name='work_days'),
    path('fix-machines/', views.show_fix_machines, name='fix_machines'),
    path('machines/', views.all_machines, name='all-machines'),
    path('report/<int:report_id>/', views.report_detail, name='report-detail'),
]

machines/urls.py
from django.urls import path 
from machines import views


app_name = 'machines'

urlpatterns = [
    # path('', views.all_machines, name='all-machines'),
    # path('detail/', views.show_detail_machines, name='detail_machines'),
    path('<int:id>/', views.detail_machine, name='detail'),
    path('description/', views.show_machines_description, name='show_machine_description'),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from main import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('logout/', views.mylogout, name='mylogout'),

    path('machines/', include('machines.urls')),
    path('driver/', include('senior_driver.urls')),

    path('machinist/', include('senior_machinist.urls')),

    path('engineer/', include('engineer.urls')),
    path('director/', include('director.urls')),

    path('administrator/', include('administrator.urls')),
]

from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns


from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

engineer/models.py
from django.db import models
from django.contrib.auth.models import User

from senior_driver.models import SeniorDriver
from machines.models import Machine


class Engineer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    date_of_birth = models.DateField(blank=True, null=False)
    telephone1 = models.CharField(max_length=15, blank=True, default='')
    telephone2 = models.CharField(max_length=15, blank=True, default='')
    avatar = models.ImageField(blank=True, upload_to="employees")


    def full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.user.username}"


class Report(models.Model):
    """ Таблиця Report - звіти від старших водіїв """
    
    filled_up = models.ForeignKey(SeniorDriver, on_delete=models.CASCADE)
    date_of_completion = models.DateTimeField(auto_now_add=True)
    updated_data = models.DateTimeField(auto_now=True)
    date = models.DateField()

    checked = models.BooleanField(blank=True, default=False)
    checked_by = models.ForeignKey(Engineer, on_delete=models.CASCADE, blank=True, null = True)

    def __str__(self):
        return f"{self.filled_up} - {self.date}"

class MachineReport(models.Model):
    """ Таблиця MachineReport - які машини були використані в ході робочого дня """
    
    report = models.ForeignKey(Report, on_delete=models.CASCADE)

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)
    
    name = models.CharField(max_length=200, blank=True)
    
    motohour = models.FloatField()
    fuel = models.FloatField()
    
    breakage = models.BooleanField(default=False)
    breakage_info = models.TextField(blank=True, null=True)
    breakage_date_start = models.DateField(blank=True, null=True)

    latFld = models.FloatField(blank=True, null=True)
    lngFld = models.FloatField(blank=True, null=True)


    def __str__(self):
        return f"{self.report.date} - {self.machine}"

    def machine_name(self):
        return f"{self.machine.full_name()}"
    

engineer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.http import Http404
from django.db.models import Q, Sum
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings

from engineer import models
from machines.models import Machine
from senior_driver.models import SeniorDriver
from engineer.models import Engineer, MachineReport
import datetime


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def hello_page(request):
    """ Стартова сторінка інженера """
    
    return render(request, 'engineer/home_page.html')


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_unforwarded_reports(request):
    """Відображення невідправлених звітів """
    
    engineer = set_engineer(request.user)

    if request.method == "POST":
        report_id = request.POST.get('report_id')
        report = models.Report.objects.get(pk=report_id)
        report.checked = True
        report.checked_by = engineer
        report.save()
        

    reports_unforwarded = models.Report.objects.filter(checked=False).order_by('-date')

    date_report_set = []
    reports_date = reports_unforwarded.values('date').annotate(total=Count('id'))
    for report_date in reports_date:
        date = report_date['date']
        queryset_rep = reports_unforwarded.filter(date=date).select_related('filled_up', 'filled_up__user')
        reports_set = []
        for query in queryset_rep:
            report_id = query.id
            driver = query.filled_up.full_name()
            brigade_name = query.filled_up.brigade_name
            machines = []
            for machine in query.machinereport_set.values('name', 'fuel', 'motohour', 'breakage'):
                name = machine['name']
                fuel = machine['fuel']
                motohour = machine['motohour']
                
                breakage = "<i class='fas fa-times' style='color:red;'></i>" if machine['breakage'] else "<i class='fas fa-check' style='color: green;'></i>"
                        
                
                machines_info = {
                    'machine_short_name': name,
                    'machine_full_name': name,
                    'fuel': fuel,
                    'motohour': motohour,
                    'breakage': breakage,
                }

                machines.append(machines_info)

            reports_set.append({'report_id': report_id, 'driver': driver, 'brigade_name': brigade_name, 'machines': machines})
        date_report_set.append({'date': date, 'report_info': reports_set})
    

    context = {
        'date_report_set': date_report_set,
    }
    return render(request, 'engineer/show_unforwarded_reports.html', context)


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_forwarded_reports(request):
    """Відображення відправлених звітів"""    
    
    reports_forwarded = models.Report.objects.filter(checked=True).order_by('-date')
    
    from_date = request.GET.get('from')
    to_date = request.GET.get('to')
    date = request.GET.get('date')
    
    # radio true - diapason, false - concrete date
    radio = True

    if from_date and to_date:
        from_date_correct = correct_date(from_date)
        to_date_correct = correct_date(to_date)
        reports_forwarded = reports_forwarded.filter(date__range = [from_date_correct, to_date_correct])

    if date:
        reports_forwarded = reports_forwarded.filter(date = correct_date(date))
        radio = False
    

    date_report_set = []
    reports_date = reports_forwarded.values('date').annotate(total=Count('id'))
    for report_date in reports_date:
        date_concrete = report_date['date']
        queryset_rep = reports_forwarded.filter(date=date_concrete).select_related('filled_up')
        reports_set = []
        for query in queryset_rep:
            report_id = query.id
            driver = query.filled_up.full_name()
            brigade_name = query.filled_up.brigade_name
            machines = []
            for machine in query.machinereport_set.values('name', 'fuel', 'motohour', 'breakage', 'breakage_info'):
                
                name = machine['name']
                fuel = machine['fuel']
                motohour = machine['motohour']
                breakage = "Є несправність" if machine['breakage'] else "Несправностей не було"
                if breakage == "Є несправність":
                    if machine['breakage_info']:
                        breakage += f"<br>Інформація: {machine['breakage_info']}"
                    else:
                        breakage = f"<br>Інформація про несправність відсутня"
                
                machines_info = {
                    'machine_short_name': name,
                    'machine_full_name': name,
                    'fuel': fuel,
                    'motohour': motohour,
                    'breakage': breakage,
                }

                machines.append(machines_info)

            reports_set.append({'report_id': report_id, 'driver': driver, 'brigade_name': brigade_name, 'machines': machines})
        date_report_set.append({'date': date_concrete, 'report_info': reports_set})


    context = {
        'from_date': from_date,
        'to_date' : to_date,
        'date': date,
        'radio': radio,
        'date_report_set': date_report_set,
    }
    return render(request, 'engineer/show_forwarded_reports.html', context)



@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_drivers(request):
    """ Старші водії """

    drivers = SeniorDriver.objects.all().order_by('brigade_name').select_related('user')
    context = {
        'drivers': drivers
    }
    return render(request, 'engineer/show_drivers.html', context)


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_drivers_detail(request, username):
    """ Деталбна інформація про водія """

    driver = SeniorDriver.objects.select_related('user').get(user__username=username)
    

    reports_driver = models.Report.objects.filter(filled_up=driver).values('id', 'date')
    machine_reports_all = MachineReport.objects.filter(Q(report_id__in = [o["id"] for o in reports_driver])).values('name', 'fuel', 'motohour','breakage', 'breakage_info', 'report_id')

    for report in reports_driver:
        report["machines"] = []
        for machine_report in machine_reports_all.filter(report_id=report["id"]):
            report["machines"].append({'machine': machine_report["name"], 'motohour': machine_report["motohour"], 'fuel': machine_report["fuel"]})

    machines = Machine.objects.filter(brigade=driver)
    paginator = Paginator(machines, 9)
    page = request.GET.get('page')
    try:
        machines = paginator.page(page)
    except EmptyPage:
        machines = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        machines = paginator.page(1)
    
    
    context = {
        'driver': driver,
        'report_set': reports_driver, 
        'machines': machines,
    }
    return render(request, 'engineer/show_driver_detail.html', context)

 
@login_required
@permission_required('engineer.full_control', raise_exception=True)
def work_days(request):
    """ Графік роботи / звітність """

    context = {}
    return render(request, 'engineer/work_days.html', context)


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_fix_machines(request):
    """ Машини які перебувають/перебували у ремонті """

    engineer = set_engineer(request.user)
    if request.method == "POST":

        machine_id = request.POST.get('breakage_machine_id')
        
        machine = models.Machine.objects.get(pk=machine_id)
        
        machine.breakage = False
        machine.breakage_info = f"{machine.breakage_info}\nUPDATE: Машина була починена {datetime.date.today()}"
        machine.fix_date = datetime.date.today()
        machine.fix_by = engineer.full_name()
        
        machine.save()

    breakage_machines = Machine.objects.filter(breakage=True).order_by('-brigade')
    context = {
        'breakage_machines': breakage_machines
    }
    return render(request, 'engineer/fix_machines.html', context)


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def all_machines(request):
    
    machiness = models.Machine.objects.all().values('name', 'number_machine', 'inventory_number', 'id')
    query = request.GET.get('q')
    if query:
        machiness = machiness.filter(
            Q(name__icontains=query) | Q(inventory_number__icontains=query) |
            Q(number_machine__icontains=query)
        ).distinct()
    paginator = Paginator(machiness, 10)
    page = request.GET.get('page')
    try:
        machines = paginator.page(page)
    except EmptyPage:
        machines = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        machines = paginator.page(1)

    context = {
        'machines': machines
    }
    return render(request, 'engineer/machines.html', context=context)


@login_required
@permission_required('engineer.full_control', raise_exception=True)
def show_fix_machines(request):
    """ Машини які перебувають/перебували у ремонті """

    engineer = set_engineer(request.user)
    if request.method == "POST":
        machine_id = request.POST.get('breakage_machine_id')
        
        machine = models.Machine.objects.get(pk=machine_id)
        
        machine.breakage = False
        machine.breakage_info = f"{machine.breakage_info}\nUPDATE: Машина була починена {datetime.date.today()}"
        machine.fix_date = datetime.date.today()
        machine.fix_by = engineer.full_name()
        
        machine.save()

machines/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

from machines import models


@login_required
def all_machines(request):

    machiness = models.Machine.objects.all()
    
    query = request.GET.get('q')
    if query:
        machiness = machiness.filter(
            Q(machine__name__icontains=query) | Q(inventory_number__icontains=query) |
            Q(number_machine__icontains=query)
        ).distinct()
    
    paginator = Paginator(machiness, 10)
    page = request.GET.get('page')
    try:
        machines = paginator.page(page)
    except EmptyPage:
        machines = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        machines = paginator.page(1)

    context = {
        'machines': machines
    }
    return render(request, 'machines/machines.html', context=context)


@login_required
def detail_machine(request, id):

    machine = get_object_or_404(models.Machine, pk=id)
    context = {
        'machine': machine,
    }
    return render(request, 'machines/detail_machine.html', context)


@login_required
def show_detail_machines(request):

    machiness = models.Machine.objects.all()
    
    query = request.GET.get('q')
    if query:
        machiness = machiness.filter(
            Q(machine__name__icontains=query) | Q(inventory_number__icontains=query) |
            Q(number_machine__icontains=query)
        ).distinct()
    
    paginator = Paginator(machiness, 10)
    page = request.GET.get('page')
    try:
        machines = paginator.page(page)
    except EmptyPage:
        machines = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        machines = paginator.page(1)

    context = {
        'machines': machines
    }
    return render(request, 'machines/detail_machines.html', context=context)



def show_machines_description(request):
    
    machines = models.MachineName.objects.all().prefetch_related('machine_set')
    context = {
        'machines': machines
    }
    return render(request, 'machines/machines_description.html', context)

templates/engineer/_base_page_engineer.html
{% extends 'base.html' %}
{% load static %}


{% block add_head_link %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    {% block add_head_link_2 %}
    {% endblock add_head_link_2 %}
{% endblock add_head_link %}





{% block title %}Інженер{% endblock %}


{% block content %}
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-dark border-right" id="sidebar-wrapper">
            <div class="sidebar-heading text-light py-5">VMM Core Production</div>
            <div class="list-group list-group-flush">
            <a href="{% url 'engineer:home-page' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-top"><i
                    class="fa fa-home"></i>Головна</a>
            <a href="{% url 'engineer:unforwarded_reports' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light"><i
                    class="fa fa-table"></i>Невідправлені звіти</a>
            <a href="{% url 'engineer:forwarded_reports' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light"><i
                    class="fa fa-table"></i>Відправлені звіти</a>
            <a href="{% url 'engineer:drivers' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light"><i
                    class="fa fa-truck"></i>Старші машиністи</a>
            <a href="{% url 'engineer:fix_machines' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-wrench"></i>Інформація про ремонт машин</a>
            <a href="{% url 'engineer:work_days' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-calendar"></i>Графік роботи</a>
            <a href="{% url 'engineer:all-machines' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-truck"></i>Всі машини</a>
        </div>
    </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
    <div id="page-content-wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <a class="nav-link text-light" href="#">Привіт, {{ user.username }}!</a>
                    <a class="nav-link text-warning" href="{% url 'mylogout' %}"><i
                            class="fa fa-arrow-right"></i>Вийти</a>
                </ul>
            </div>
        </nav>
        {% block content_page %}
        КОД ОСН СТРАНИЦЫ
        {% endblock content_page %}
    </div>

{% block add_another_html %}
{% endblock add_another_html %}


<style>
    body {
        overflow-x: hidden;
    }
    .fa {
        margin-right: 10px;
    }
    #sidebar-wrapper {
        min-height: 100vh;
        margin-left: -15rem;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
    }
    #sidebar-wrapper .sidebar-heading {
        padding: 0.875rem 1.25rem;
        font-size: 1.2rem;
    }
    #sidebar-wrapper .list-group {
        width: 15rem;
    }
    #page-content-wrapper {
        min-width: 100vw;
    }
    #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
    }
    @media (min-width: 768px) {
        #sidebar-wrapper {
            margin-left: 0;
        }
        #page-content-wrapper {
            min-width: 0;
            width: 100%;
        }
        #wrapper.toggled #sidebar-wrapper {
            margin-left: -15rem;
        }
    }
</style>    

{% block add_style %}
{% endblock add_style %}


{% block add_js %}
{% endblock add_js %}

{% endblock content %}

templates/engineer/home_page.html
{% extends 'engineer/_base_page_engineer.html' %}

{% block content_page %}

        <div class="container-fluid">
            <h1 class="mt-4 text-center">Головна сторінка інженера</h1>
            <div class="content-text">
                <div class="row justify-content-center">
                    <div class="col-10">
                <p class="alert">Основна функція програми для інженера - перевірка звітів, які надійшли від старшого водія і після перевірки передати звіт директору</p>
                <ul class="alert">
                    <li>
                        <p>У вкладці <a href="{% url 'engineer:unforwarded_reports' %}">Невідправлені звіти</a> знаходяться звіти, які прийли від старших машиністів та ще не передані керівництву<br/>
                            Після ознайомлення зі звітом Ви можете відправити їх керівництву. Якщо є якісь деталі - треба зв'язатись зі старшим машиністом, який заповнював звіт.</p>
                        <p>
                    </li>
                    <li><p>
                    У вкладці <a href="{% url 'engineer:forwarded_reports'%}">"Відправлені звіти"</a> знаходяться всі звіти, які були передані керівництву.
                </p>
                    </li>
                    <li><p>
                        Вкладка <a href="{% url 'engineer:drivers'%}">"Старші машиністи"</a> містить інформацію про старших машиністів, 
                        номера телефонів, email-адреси та детальну інформацію про кожного з них 
                    </p></li>
                    <li><p>
                        Вкладка <a href="{% url 'engineer:fix_machines'%}">"Інформація про ремонт машини"</a> містить машини, які у даний момент часу знаходяться в ремонтному цеху.
                        Коли з'являється Інформація про відремонтування машини, Вам потрібно вивести машину з ремонту.
                    </p></li>
                    <li><p>
                        Вкладка <a href="{% url 'engineer:work_days'%}">"Графік роботи"</a> містить деяку Вашу інформацію, графік виходу на роботу, 
                        телефони та email-адреси для зв'язку зі старшими машиністами і директором  
                    </p></li>
                    <li><p>
                        Вкладка <a href="{% url 'engineer:all-machines'%}">"Всі машини"</a> містить інформацію про всі  машини які є у фірми. 
                        Можна подивитись детальну інформацію про конкретну машину, знайти необхідну машину за назвою або інвентарному номеру, або номеру машини. 
                        А також подивитись опис, вигляд, прзначення різних колійних машин. 
                    </p></li>
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock content_page %}
        

{% block add_style %}
    <style> 
        p{
            font-size: larger;
            text-align: justify;
            line-height: 2;
        }       
    </style>
{% endblock add_style %}
        

templates/engineer/machines.html
{% extends 'engineer/_base_page_engineer.html' %}
{% block title %}Всі машини{% endblock %}
{% block content_page %}
<div class="content alert">
    <h2 class="alert text-center">Всі машини</h2>
    {% include 'machines/machines.html' %}
</div>

{% endblock content_page %}

templates/engineer/show_driver_detail.html
{% extends 'engineer/_base_page_engineer.html' %}

{% block title %}Сторінка машиніста {{driver.user.username}}{% endblock title %}

{% block content_page %}

<div class="container-fluid">
    <h2 class="mt-4 text-center">Інформація про машиніста</h2>

    <div class="content-text my-4 pt-4">
        <div class="row">
            <div class="col-4 offset-2">
                <div class="card shadow bg-white rounded" style="width: 18rem;">
                    <img src="{{driver.avatar.url}}" style="height: 20rem;" alt="{{driver.full_name}}">
                    <div class="card-body">
                        <h4 class="text-center">{{driver.full_name}}</h4>
                        <h5 class="text-center">@{{driver.user.username}}</h5>
                        <p class="card-text text-center">Дата народження<br> {{driver.date_of_birth |date:"j E, Y"}}</p>
                        <p class="card-text text-center"><i class="fa fa-envelope"></i> <span><a href="mailto:{{driver.user.email}}" style="color: black;">{{driver.user.email}}</a></span></p>
                        <p class="card-text text-center"><i class="fa fa-phone" aria-hidden="true"></i> <span>{{driver.phones}}</span></p>
                    </div>
                </div>
            </div>

            <div class="col-4">

                <p class="text-center font-italic" style="font-size: larger;">Машини, які закріплені за старшим машиністом</p>
                {% if machines.paginator.num_pages > 1 %} 
                <nav aria-label="Page navigation">
                    {# Из-за не работают некоторые классы css/mdb.min.css #}
                    <ul class="pagination justify-content-center">
          
                        {% if machines.has_previous %}            
                        <li class="page-item"> 
                        <a class="page-link" href="?page={{machines.previous_page_number}}" aria-label="Previous">
                          <span aria-hidden="true">&laquo;</span>
                          <span class="sr-only">Previous</span>
                        </a></li> 
                        {% else %}
                        <li class="page-item"> 
                        <a class="page-link" href="?page=1" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                            <span class="sr-only">Previous</span>
                          </a></li>
                        {% endif %}
                        
                        {% for i in machines.paginator.page_range %}
                            {% if machines.number == i %}
                            <li class="page-item active">
                                <span class="page-link">
                                  {{i}}
                                  <span class="sr-only">(current)</span>
                                </span>
                              </li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{i}}" title="{{i}}">{{i}}</a></li>
                            {% endif %}
                        {% endfor %}
                            
                            
                        {% if machines.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{machines.next_page_number}}" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">Next</span>
                            </a>
                          </li>
                        {% else %}
                        <li class="page-item"><a class="page-link" href="#" onclick="return false;" aria-label="Next">
                              <span aria-hidden="true">&raquo;</span>
                              <span class="sr-only">Next</span>
                            </a></li>
                          {% endif %}
                    </ul>
                </nav>
                {% endif %}

                <div class="list-group">
                    {% for machine in machines %}
                        <a href="{% url 'machines:detail' machine.id %}" class="list-group-item list-group-item-action" title="Переглянути машину детально">{{machine.name}} №{{machine.number_machine}} [IN-{{machine.inventory_number}}]</a>
                    {% endfor %}
                </div>
            </div> 
        </div>
        <div class="col-8 offset-2 pt-4 mt-4">
            <div class="driver_reports">

                <h3 class="mb-4 text-center">Звіти водія</h3>
                {% if report_set %}
                <div class="shadow bg-white rounded my-5 p-4">
            
                    {% for report in report_set %}
                    <div class="row">
                        <div class="col-6">
                            <h5 class="font-weight-bold text-warning">Звіт №{{report.id}}</h5>
                            <p><span class="font-weight-bold">Звіт за:</span> {{ report.date }}</p>
                        </div>
                        <div class="col-6 text-center pt-1">
                            <p><a href="{% url 'engineer:report-detail' report.id %}" class="btn btn-warning">детально про звіт</a></p>
                        </div>
                    </div>
                    
                    
                    {% if report.machines %}
                    <table class="table text-center">
                        <tr>
                            <td class="font-weight-bold">Машина</td>
                            <td class="font-weight-bold">Мотогодини</td>
                            <td class="font-weight-bold">Використано палива</td>
                        </tr>
                        {% for data in report.machines %}
                        <tr>
                            <td>{{data.machine}}</td>
                            <td>{{data.motohour}}</td>
                            <td>{{data.fuel}}</td>
                        </tr>
                        {% endfor %}
                    </table>
                    {% endif %}

                    <br>
                    <hr>
                    {% endfor %}

                </div>
                {% else%}
                <p>У цього старшого водія звітів немає</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock content_page %}


{% block add_style %}
<style>
    /* TABLE----------------------- */
    .table_dark {
        font-size: 14px;
        width: 100%;
        text-align: left;
        border-collapse: collapse;
        background: #252F48;
        margin: 10px;
    }

    .table_dark th {
        color: #EDB749;
        border-bottom: 1px solid #37B5A5;
        padding: 12px 17px;
    }

    .table_dark td {
        color: #CAD4D6;
        border-bottom: 1px solid #37B5A5;
        border-right: 1px solid #37B5A5;
        padding: 20px 27px;
    }

    .table_dark tr:last-child td {
        border-bottom: none;
    }

    .table_dark td:last-child {
        border-right: none;
    }

    .table_dark tr:hover td {
        text-decoration: underline;
    }
</style>
{% endblock add_style %}