main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from main import views, settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),

    path('logout/', views.mylogout, name='mylogout'),

    path('machines/', include('machines.urls')),
    path('driver/', include('senior_driver.urls')),

    path('machinist/', include('senior_machinist.urls')),

    path('engineer/', include('engineer.urls')),
    path('director/', include('director.urls')),

    path('administrator/', include('administrator.urls')),
]

from django.conf import settings

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns


from django.contrib.staticfiles.urls import static
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

senior_machinist/urls.py
from django.urls import path
from senior_machinist import views


app_name = 'machinist'

urlpatterns = [
    path('', views.home_page, name='home-page'),
    path('machine/', views.my_machine, name='machine'),
    path('machine/status/', views.machine_status, name='machine-status'),
    path('contact/', views.management_contact, name='management-contact'),
    path('members/', views.brigade_members, name='brigade-members'),
    path('route-sheet/', views.route_sheet, name='route-sheet'),
    path('route-sheet/machine-info', views.machine_working_fill, name='machine-fill'),
    path('show-route-sheets/', views.show_route_sheet, name='show-route-sheet'),
    path('route-sheet/<int:route_sheet_id>/', views.route_sheet_detail, name='route-sheet-detail'),
]

senior_machinist/models.py
from django.db import models
from django.contrib.auth.models import User
from machines.models import Machine
from engineer.models import Engineer


class SeniorMachinist(models.Model):
    """ Старший машиніст """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    brigade_name = models.CharField(blank=True, max_length=50)
    telephone1 = models.CharField(max_length=30, blank=True, default='')
    telephone2 = models.CharField(max_length=30, blank=True, default='')
    avatar = models.ImageField(blank=True, upload_to="employees", default='no-image.png')
    
    date_of_birth = models.DateField(blank=True, null=True)
    date_start_work = models.DateField(blank=True, null=True)

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE, blank=True, null=True)

    def full_name(self):
        return f"{self.user.last_name} {self.user.first_name}"

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.user.username}"


class BrigadeMembers(models.Model):
    """ Члени бригади (підконтрольні машиністу) """

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    telephone1 = models.CharField(max_length=30, blank=True, default='')
    telephone2 = models.CharField(max_length=30, blank=True, default='')
    
    HELPER = 'hlp'
    MACHINIST = 'mnst'
    JOB_TITLE_CHOICES = [
        (HELPER, 'допоможний персонал'),
        (MACHINIST, 'машиніст'),
    ]
    job_title = models.CharField(
        max_length=4,
        choices=JOB_TITLE_CHOICES,
        default=MACHINIST,
    )

    seniormachinist = models.ForeignKey(SeniorMachinist, on_delete=models.CASCADE)

    def phones(self):
        phones = self.telephone1
        if self.telephone2:
            phones += ', ' + self.telephone2
        return phones

    def __str__(self):
        return f"{self.last_name} {self.first_name}"


class TempReport(models.Model):
    """ Таблиця Report - звіти від старших машиністів """
    
    filled_up = models.ForeignKey(SeniorMachinist, on_delete=models.CASCADE)
    date_of_completion = models.DateTimeField(auto_now_add=True)
    updated_data = models.DateTimeField(auto_now=True)
    date = models.DateField(unique=True)

    checked = models.BooleanField(blank=True, default=False)
    checked_by = models.ForeignKey(Engineer, on_delete=models.CASCADE, blank=True, null = True)

    NO = 'no'
    START = 'strt'
    PART = 'part'
    FULL = 'full'
    FORWARD_I = 'fwdi'
    CHECKED_I = 'chki'
    FORWARD_D = 'fwdd'
    CHECKED_D = 'chkd'
    STAGE_CHOICES = [
        (NO, 'Пустий звіт'),
        (START, 'Початок створення'),
        (PART, 'Частично заповнений'),
        (FULL, 'Заповнений'),
        (FORWARD_I, 'Відісланий інженеру'),
        (CHECKED_I, 'Звіт перевірений інженером'), 
        (FORWARD_D, 'Відісланий директору'),
        (CHECKED_D, 'Звіт перевірений директором'), 
    ]
    stage = models.CharField(
        max_length=4,
        choices=STAGE_CHOICES,
        default=NO,
    )

    machine = models.ForeignKey(Machine, on_delete=models.CASCADE)

  
    motohour = models.FloatField(blank=True, null=True)
    km = models.FloatField(blank=True, null=True)
    fuel = models.FloatField(blank=True, null=True)
    maslo = models.FloatField(blank=True, null=True)

    breakage = models.BooleanField(default=False)
    breakage_info = models.TextField(blank=True, null=True)
    breakage_date_start = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.filled_up} - {self.date}"


class BrigadeInfoReport(models.Model):
    """ Інформація про бригаду у звіті """

    member = models.ForeignKey(BrigadeMembers, on_delete=models.CASCADE)
    report = models.ForeignKey(TempReport, on_delete=models.CASCADE)
    date_time_from = models.DateTimeField(blank=True, null=True)
    date_time_to = models.DateTimeField(blank=True, null=True)
    
    NOT_ALLOWED = 'na'
    UNKNOW = 'uk'
    ALLOWED = 'al'
    HEALTH = 'hl'
    PASSED = 'ps'
    MEDICAL_CHECK = [
        (NOT_ALLOWED, 'не допущенний'),
        (ALLOWED, 'допущений'),
        (HEALTH, 'здоровий'),
        (PASSED, 'пройдено'),
        (UNKNOW, 'невідомо'),
    ]
    medical_check_before = models.CharField(
        max_length=2,
        choices=MEDICAL_CHECK,
        default=UNKNOW,
    )
    medical_check_after = models.CharField(
        max_length=2,
        choices=MEDICAL_CHECK,
        default=UNKNOW,
    )

    def __str__(self):
        return f"{self.member}"


class MachineWorkingReport(models.Model):
    """ Таблиця MachineWorkingReport - де машина працювала в ході робочого дня """

    report = models.ForeignKey(TempReport, on_delete=models.CASCADE)

    client = models.CharField(max_length=20, blank=True, null=True)
    station_from = models.CharField(max_length=50, blank=True, null=True)
    station_to = models.CharField(max_length=50, blank=True, null=True)
    departure_time = models.DateTimeField(blank=True, null=True)
    arrival_time = models.DateTimeField(blank=True, null=True)
    
    latFld = models.FloatField(blank=True, null=True)
    lngFld = models.FloatField(blank=True, null=True)
    time_from = models.DateTimeField(blank=True, null=True)
    time_to = models.DateTimeField(blank=True, null=True)

    place_working = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    workday_production = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return f"{self.report.date}"

class MasloInfoReport(models.Model):

    report = models.OneToOneField(TempReport, on_delete=models.CASCADE, blank=True, null=True)
    marka = models.CharField(max_length=30, blank=True, null=True)
    vidano = models.CharField(max_length=30, blank=True)
    maslo_before = models.FloatField(blank=True, null=True)
    maslo_after = models.FloatField(blank=True, null=True)
    info = models.CharField(max_length=200, blank=True, null=True)


class MotoAndFuelInfoReport(models.Model):
    
    report = models.OneToOneField(TempReport, on_delete=models.CASCADE, blank=True, null=True)
    motohour_before = models.FloatField(blank=True, null=True)
    motohour_after = models.FloatField(blank=True, null=True)
    km_before = models.FloatField(blank=True, null=True)
    km_after = models.FloatField(blank=True, null=True)
    info = models.CharField(max_length=200, blank=True, null=True)

templates/senior-machinist/part/_base_page_machinist.html
{% extends 'base.html' %}
{% load static %}


{% block add_head_link %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    {% block add_head_link_2 %}
    {% endblock add_head_link_2 %}
{% endblock add_head_link %}




{% block title %}Старший водій{% endblock %}


{% block content %}
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-dark border-right" id="sidebar-wrapper">
            <div class="sidebar-heading text-light py-5">VMM Core Production</div>
            <div class="list-group list-group-flush">
            <a href="{% url 'machinist:home-page' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-top"><i
                    class="fa fa-home"></i>Головна</a>
            <a href="{% url 'machinist:route-sheet'%}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                class="fa fa-table"></i>Створити марш. лист</a>
            <a href="{% url 'machinist:show-route-sheet'%}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-calendar"></i>Мої марш. листи</a>
            <a href="{% url 'machinist:machine' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-truck"></i>Моя машина</a>
            <a href="{% url 'machinist:machine-status' %}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-wrench"></i>Стан машини</a>
            <a href="{% url 'machinist:management-contact'%}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i
                    class="fa fa-phone"></i>Керівництво</a>
            <a href="{% url 'machinist:brigade-members'%}"
                class="list-group-item list-group-item-action bg-dark text-light border-light border-bottom"><i 
                    class="fa fa-address-card"></i>Працівники бригади</a>
        </div>
    </div>
        <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                    <a class="nav-link text-light" href="#">Привіт, {{ user.username }}!</a>
                    <a class="nav-link text-warning" href="{% url 'mylogout' %}"><i
                            class="fa fa-arrow-right"></i>Вийти</a>
                </ul>
            </div>
        </nav>
        {% block content_page %}
        КОД ОСН СТРАНИЦЫ
        {% endblock content_page %}
    </div>

{% block add_another_html %}
{% endblock add_another_html %}


<style>
    body {
        overflow-x: hidden;
    }
    .fa {
        margin-right: 10px;
    }
    #sidebar-wrapper {
        min-height: 100vh;
        margin-left: -15rem;
        -webkit-transition: margin .25s ease-out;
        -moz-transition: margin .25s ease-out;
        -o-transition: margin .25s ease-out;
        transition: margin .25s ease-out;
    }
    #sidebar-wrapper .sidebar-heading {
        padding: 0.875rem 1.25rem;
        font-size: 1.2rem;
    }
    #sidebar-wrapper .list-group {
        width: 15rem;
    }
    #page-content-wrapper {
        min-width: 100vw;
    }
    #wrapper.toggled #sidebar-wrapper {
        margin-left: 0;
    }
    @media (min-width: 768px) {
        #sidebar-wrapper {
            margin-left: 0;
        }
        #page-content-wrapper {
            min-width: 0;
            width: 100%;
        }
        #wrapper.toggled #sidebar-wrapper {
            margin-left: -15rem;
        }
    }
</style>    

{% block add_style %}
{% endblock add_style %}


{% block add_js %}
{% endblock add_js %}

{% endblock content %}

templates/senior-machinist/part/_brigade_info_report.html
<div class="col-12 mt-4">
    <h4 class="text-center pb-4">Заповнення даних про бригаду</h4>
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" name='temp_report_id' value="{{temp_report.id}}">
        <input type="hidden" name='date' value="{{date}}">
        <table class="table table-bordered text-center">
            <tr>
                <th rowspan="2">Працівник</th>
                <th colspan="2">Час роботи</th>
                <th colspan="2">Передрейсовий мед. огляд</th>
                <th colspan="2">Післярейсовий мед. огляд</th>
            </tr>
            <tr>
                <th>початок</th>
                <th>кінець</th>
                <th>прізвище</th>
                <th>статус</th>
                <th>прізвище</th>
                <th>статус</th>
            </tr>
            {% for member in members %}
                <tr>
                    <input type="hidden" name="member_id" value="{{member.id}}">
                    <td> {{member.get_job_title_display}} <b>{{member.last_name}} {{member.first_name}}</b></td>
                    <td><input type="time" class="form-control" name="date_time_from" list="time-list"></td>
                    <td><input type="time" class="form-control" name="date_time_to" list="time-list"></td>
                    <td><input type="text" class="form-control" size="10"></td>
                    <td>
                        <select class="form-control" id="medical_check_before{{member.id}}" style="width:120px" name="medical_check_before">
                            <option value="ps" selected>пройдено</option>
                            <option value="na">не допущений</option>
                            <option value="al">допущений</option>
                            <option value="uk">невідомо</option>
                        </select>
                    </td>
                    <td><input type="text" class="form-control" size="10"></td>
                    <td>
                        <select class="form-control" id="medical_check_after{{member.id}}" style="width:120px" name="medical_check_after">
                            <option value="ps" selected>пройдено</option>
                            <option value="na">не допущений</option>
                            <option value="hl">здоровий</option>
                            <option value="uk">невідомо</option>
                        </select>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <div class="col-12 text-center">
            <input type="submit" class="btn btn-primary" name="sendDataBrigade" value="Зберегти дані роботі бригади">
        </div>
    </form>
</div>
<script>
    $(document).ready(function(){
        var num = 'na';
        {% for member in members %}
        $("#medical_check_before{{member.id}}").on('change', function() {
            if ($(this).val() == 'na'){
                $('#medical_check_after{{member.id}} [value="na"]').prop('selected', true);
            }
            else {
                $('#medical_check_after{{member.id}}').prop('disabled', false);
            }
        });
        {% endfor %}
    });
</script>

templates/senior-machinist/part/_full_report.html
<div>
    <h2 class="text-center">
        Заповнення данних
    </h2>
</div>
<div class="col-10 offset-1">
    <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">1.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Дані про бригаду</span></p>                        
    <form action="" method="post">
        {% csrf_token %}
        <input type="hidden" value="{{temp_report.id}}">
        <table class="table">
            <tr>
                <th rowspan="3">Посада</th>
                <th rowspan="3">Прізвище</th>
                <th rowspan="2" colspan="2">Час роботи</th>
                <th colspan="4">Проходження медичних оглядів</th>
            </tr>
            <tr>
                <th colspan="2">передрейсовий</th>
                <th colspan="2">післярейсовий</th>
            </tr>
            <tr>
                <th>початок</th>
                <th>кінець</th>
                <th>прізвище</th>
                <th>статус</th>
                <th>прізвище</th>
                <th>статус</th>
            </tr>
            {% for member in members %}
                <tr>
                    <input type="hidden" name="member_id" value="{{member_id}}">
                    <td>{{member.get_job_title_display}}</td>
                    <td>{{member.last_name}} {{member.first_name}}</td>
                    <td><input type="time" name="date_time_from" list="time-list"></td>
                    <td><input type="time"  name="date_time_to" list="time-list"></td>
                    <td><input type="text"></td>
                    <td>
                        <select class="form-control" id="medical_check_before" name="medical_check_before">
                            <option value="na">не допущений</option>
                            <option value="al">допущений</option>
                            <option value="uk" selected>невідомо</option>
                        </select>
                    </td>
                    <td><input type="text"></td>
                    <td>
                        <select class="form-control" id="medical_check_after" name="medical_check_after">
                            <option value="na">не допущений</option>
                            <option value="al">допущений</option>
                            <option value="uk" selected>невідомо</option>
                        </select>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input type="submit" name="sendDataBrigade" value="Відправити дані">
    </form>
    

    <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">2.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Показання спідометра, лічильника мотогодин</span></p>
    <table class="table">
        <tr>
            <th colspan="2">Показання спідометра, лічильника мотогодин при виїзді</th>
            <th colspan="2">Показання спідометра, лічильника мотогодин при поверненні</th>
            <th rowspan="2">Усього пробіг, км</th>
            <th rowspan="2">Усього відпрацьовано мотогодин</th>
        </tr>
        <tr>
            <th>км</th>
            <th>мотогодини</th>
            <th>км</th>
            <th>мотогодини</th>
        </tr>
        <tr>
            <td><input type="number" id="km_before" step="0.1"></td>
            <td><input type="number" id="moto_before" step="1"></td>
            <td><input type="number" id="km_after" step="0.1"></td>
            <td><input type="number" id="moto_after" step="1"></td>
            <td><span id="km_balance"></span></td>
            <td><span id="moto_balance"></span></td>
        </tr>
    </table>

    <div>
        <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">3.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Рух паливно-мастильних матеріалів</span></p>
        <table class="table">
            <tr>
                <th>Марка палива, мастила</th>
                <th>Видано</th>
                <th>Залишок при виїзді</th>
                <th>Залишок при поверненні</th>
                <th>Примітки</th>
            </tr>
            <tr>
                <td><input type="text" id="marka" name="marka"></td>
                <td><input type="text" id="vidano" name="vidano"></td>
                <td><input type="number" id="maslo_before" name="maslo_before" step="0.1"></td>
                <td><input type="number" id="maslo_after" name="maslo_after" step="0.1"></td>
                <td><input type="text" id="info"></td>
            </tr>
        </table>
    </div>

    <div>
        <p class="offset-1 pb-4" style="font-size: larger;"><span style="font-weight: bold;" class="pr-4">3.</span> <i class="fa fa-train" aria-hidden="true"></i><span class="pr-2"> Дані про роботу машини</span></p>
        <table class="table">
            <tr>
                <th rowspan="2">Замовник</th>
                <th rowspan="2">Станція відправлення</th>
                <th rowspan="2">Станція призначення</th>
                <th colspan="2">Час</th>
                <th rowspan="2">Назва виконаних робіт</th>
                <th rowspan="2">Місце робіт</th>
                <th rowspan="2">Виробіток за робочий день</th>
            </tr>
            <tr>
                <th>Початку робіт у "вікно"</th>
                <th>Закінчення робіт у "вікно"</th>
            </tr>
            <tr>
                <td><input type="text" id="client" name="client"></td>
                <td><input type="text" id="station_from" name="station_from"></td>
                <td><input type="text" id="station_to" name="station_to"></td>
                <td><input type="time" name="departure_time" list="time-list"></td>
                <td><input type="time"  name="arrival_time" list="time-list"></td>
                <td><input type="text" id="description">
                <td><input type="text" id="place_working"></td>
                <td><input type="text" id="workday_production"></td>
            </tr>
        </table>
    </div>
    <button type="submit">Відправити</button>
</div>

<datalist id="time-list">
    <option value="09:00" ></option>
    <option value="10:00" label=""></option>
    <option value="11:00" label=""></option>
    <option value="12:00" label=""></option>
    <option value="14:00" label=""></option>
    <option value="16:00" label=""></option>
    <option value="18:00" label=""></option>
    <option value="20:00" label=""></option>
    <option value="22:00" label=""></option>
</datalist>
<script>
    var km_before = document.getElementById("km_before");
    var km_after = document.getElementById("km_after");
    var km_balance = document.getElementById("km_balance");

    var moto_before = document.getElementById("moto_before");
    var moto_after = document.getElementById("moto_after");
    var moto_balance = document.getElementById("moto_balance");

    function setKmBalance() {
        if (km_before.value && km_after.value) {
            km_balance.textContent =  parseFloat(km_after.value) - parseFloat(km_before.value)
        }
    }
    function setMotoBalance() {
        if (moto_before.value && moto_after.value) {
            moto_balance.textContent = parseFloat(moto_after.value) - parseFloat(moto_before.value)
        }
    }

    km_before.addEventListener("input", setKmBalance)
    km_after.addEventListener("input", setKmBalance)
    moto_before.addEventListener("input", setMotoBalance)
    moto_after.addEventListener("input", setMotoBalance)
</script>

templates/senior-machinist/part/_machine_working_info_report.html
<div class="col-12">
<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name='temp_report_id' value="{{temp_report.id}}">
    <input type="hidden" name='date' value="{{date}}">
    {% for member in members %}
        <input type="hidden" name="member_id" value="{{member.id}}">
    {% endfor %}
    <div class="col-12">
    <table class="table">
        <tr>
            <th rowspan="2">Замовник</th>
            <th rowspan="2">Станція відправлення</th>
            <th rowspan="2">Станція призначення</th>
            <th colspan="2">Час</th>
            <th rowspan="2">Назва виконаних робіт</th>
            <th rowspan="2">Місце робіт</th>
            <th rowspan="2">Виробіток за робочий день</th>
        </tr>
        <tr>
            <th>Початку робіт у "вікно"</th>
            <th>Закінчення робіт у "вікно"</th>
        </tr>
        <tr>
            <td><input type="text" id="client" name="client"></td>
            <td><input type="text" id="station_from" name="station_from"></td>
            <td><input type="text" id="station_to" name="station_to"></td>
            <td><input type="time" name="departure_time" list="time-list"></td>
            <td><input type="time" name="arrival_time" list="time-list"></td>
            <td><input type="text" name="description" id="description">
            <td><input type="text" name="place_working" id="place_working"></td>
            <td><input type="text" name="workday_production" id="workday_production"></td>
        </tr>
    </table>
</div>
    <div class="col-12 text-center">
        <input type="submit" name="sendDataMachineWorking" class="btn btn-primary" value="Зберегти дані про роботу машини">
    </div>
</form>
</div>

<datalist id="time-list">
    <option value="09:00" ></option>
    <option value="10:00" label=""></option>
    <option value="11:00" label=""></option>
    <option value="12:00" label=""></option>
    <option value="14:00" label=""></option>
    <option value="16:00" label=""></option>
    <option value="18:00" label=""></option>
    <option value="20:00" label=""></option>
    <option value="22:00" label=""></option>
</datalist>

templates/senior-machinist/part/_maslo_info_report.html
<div class="col-12 mt-4">
<h4 class="text-center pb-2">Заповнення даних руху паливно-мастильних матеріалів</h4>
<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name='temp_report_id' value="{{temp_report.id}}">
    <input type="hidden" name='date' value="{{date}}">
    {% for member in members %}
        <input type="hidden" name="member_id" value="{{member.id}}">
    {% endfor %}
    <table class="table table-bordered text-center mt-4">
        <tr>
            <th>Марка палива, мастила</th>
            <th>Видано</th>
            <th>Залишок при виїзді</th>
            <th>Залишок при поверненні</th>
            <th>Примітки</th>
        </tr>
        <tr>
            <td><input type="text" class="form-control" id="marka" name="marka"></td>
            <td><input type="text" class="form-control" id="vidano" name="vidano"></td>
            <td><input type="number" class="form-control" id="maslo_before" name="maslo_before" step="0.1"></td>
            <td><input type="number" class="form-control" id="maslo_after" name="maslo_after" step="0.1"></td>
            <td><input type="text" class="form-control" id="info"></td>
        </tr>
    </table>
    <div class="col-12 text-center">
        <input type="submit" name="sendDataMasloInfo" class="btn btn-primary" value="Зберегти дані руху паливно-мастильних матеріалів">
    </div>
</form>
</div>

templates/senior-machinist/part/_moto_fuel_info_report.html
<div class="col-12 mt-4">
    <h4 class="text-center pb-4">Заповнення даних показання спідометра, лічильника мотогодин</h4>
<form action="" method="post">
    {% csrf_token %}
    <input type="hidden" name='temp_report_id' value="{{temp_report.id}}">
    <input type="hidden" name='date' value="{{date}}">
    {% for member in members %}
        <input type="hidden" name="member_id" value="{{member.id}}">
    {% endfor %}
    <table class="table table-bordered text-center mt-4">
        <tr>
            <th colspan="2">Показання спідометра, лічильника мотогодин при виїзді</th>
            <th colspan="2">Показання спідометра, лічильника мотогодин при поверненні</th>
        </tr>
        <tr>
            <th>км</th>
            <th>мотогодини</th>
            <th>км</th>
            <th>мотогодини</th>
        </tr>
        <tr>
            <td><input type="number" class="form-control" id="km_before" name="km_before" step="0.1"></td>
            <td><input type="number" class="form-control" id="moto_before" name="motohour_before" step="1"></td>
            <td><input type="number" class="form-control" id="km_after" name="km_after" step="0.1"></td>
            <td><input type="number" class="form-control" id="moto_after" name="motohour_after" step="1"></td>
        </tr>
    </table>
    <div class="col-10 offset-1 row">
        <div class="col-6 text-center">
            <p>
                Пройдено кілометрів <span class="mr-3 font-weight-bold" id="km_balance">-</span>
            </p>
        </div>
        <div class="col-6 text-center">
            <p>
                Пройдено мотогодин <span class="mr-3 font-weight-bold" id="moto_balance">-</span>
            </p>
        </div>
    </div>
    
    
    <div class="col-12 text-center">
        <input type="submit" name="sendDataMotoFuel" class="btn btn-primary" value="Зберегти дані спідометра та мотогодин">
    </div>
    
</form>
</div>
<script>
    var km_before = document.getElementById("km_before");
    var km_after = document.getElementById("km_after");
    var km_balance = document.getElementById("km_balance");

    var moto_before = document.getElementById("moto_before");
    var moto_after = document.getElementById("moto_after");
    var moto_balance = document.getElementById("moto_balance");

    function setKmBalance() {
        if (km_before.value && km_after.value) {
            km_balance.textContent =  parseFloat(km_after.value) - parseFloat(km_before.value)
        }
    }
    function setMotoBalance() {
        if (moto_before.value && moto_after.value) {
            moto_balance.textContent = parseFloat(moto_after.value) - parseFloat(moto_before.value)
        }
    }

    km_before.addEventListener("input", setKmBalance)
    km_after.addEventListener("input", setKmBalance)
    moto_before.addEventListener("input", setMotoBalance)
    moto_after.addEventListener("input", setMotoBalance)
</script>